
Update challenges set environmental_issues='<p>Have you ever wondered what sources are used to generate the electricity you use?&nbsp; Across the globe, 65% of electricity is generated by fossil fuels. Fossil fuels are not renewable sources and the more electricity we consume, the faster these resources will be depleted. They also contribute to air pollution by emitting harmful pollutants. Switching to cleaner sources of energy is the ultimate solution to this global problem. But, today this process is large-scale and costly.</p>
<p>How do bulbs glow?</p>
<p><span style="font-size: 13.0pt; font-family: ''Calibri'',sans-serif;">The traditional incandescent bulbs basically produce light by becoming extremely hot. When the filament of the bulb heats up to high degrees, it produces light. Since we only want light, any heat produced is wasted energy. These bulbs use 90% of the electricity to just get hot! </span></p>' where id=1 ;
Update challenges set participation_steps ='<p><strong>You can always start small and start today! </strong></p>
<p>Consume less electricity by opting for alternatives to traditional bulbs with energy saving options such as:</p>
<ul style="margin-top: 0in;">
<li style="margin-bottom: 8.0pt;">CFL lamps</li>
<li style="margin-bottom: 8.0pt;">LED lamps</li>
</ul>
<p>These will not only consume 25%-80% of less energy, they will also last 3-25 times longer and thus saving you some money and the planet some energy!</p>
<p><span style="font-size: 13.0pt; font-family: ''Calibri'',sans-serif;">Try it out, by replacing 5 of your most frequently used traditional bulbs with energy saving bulbs.</span></p>' where id=1 ;

Update challenges set reference ='<p>What is your relationship with energy? Watch this Ted talk to learn &lsquo;The four things you need to know about the energy you use.&rsquo; - <a href="https://www.ted.com/talks/jordan_wirfs_brock_the_four_things_you_need_to_know_about_the_energy_you_use">https://www.ted.com/talks/jordan_wirfs_brock_the_four_things_you_need_to_know_about_the_energy_you_use</a></p>
<p>Beginner&rsquo;s guide to energy saving light bulbs - <a href="https://www.ovoenergy.com/guides/energy-guides/energy-saving-light-bulbs.html">https://www.ovoenergy.com/guides/energy-guides/energy-saving-light-bulbs.html</a></p>
<p><span style="font-size: 13.0pt; font-family: ''Calibri'',sans-serif;">What energy savers are the best for you &ndash; CFL or LED?&nbsp; Find out by reading this blog post - <a href="https://blog.constellation.com/2016/03/25/led-vs-cfl-bulbs/">https://blog.constellation.com/2016/03/25/led-vs-cfl-bulbs/</a></span></p>' where id=1 ;



Update challenges set environmental_issues='<p>When you dispose an old item, do you ever think about where it ends up? Most of our solid waste ends up in landfills, polluting the environment and increasing the piles of garbage. What if you had upcycled the discarded item instead?</p>
<p>Upcycling is taking something that is considered waste and repurposing it.&nbsp;This process makes the rejected article more functional or beautiful than what it previously was. That&rsquo;s why it&rsquo;s called upcycling, because the value of the item is increased!</p>
<p>There are two ways to approach upcycling. You can either think of something that you&rsquo;d like to create or think of something that you&rsquo;d like to use. Either way, make sure to use only ready resources available to you at hand. Since upcycling existing resources means that we don&rsquo;t have to use any new raw materials in the production process, it is a great way to reuse materials and reduce our footprint.</p>
<p>Our planet should not have to bear the environmental costs of all of our waste &ndash; help out today by upcycling something you were about to throw away.</p>' where id=2 ;

 Update challenges set participation_steps ='<p>Join hands with your team and complete this challenge to create a bigger impact!</p>
<ul>
<li style="padding-left:10px;">Bring together your team members for the challenge.</li>
<li style="padding-left:10px;">Together upcycle three old items of yours that you are not using anymore.</li>
</ul>' where id=2 ;

 Update challenges set reference ='
<p><strong>Read more about Upcycling: </strong><a href="https://hipcycle.com/what-is-upcycling"><strong>https://hipcycle.com/what-is-upcycling</strong></a></p>
<p><strong>50 Creative ways to upcycle old things: </strong><a href="https://twistedsifter.com/2012/06/creative-ways-to-repurpose-reuse-and-upcycle-old-things/"><strong>https://twistedsifter.com/2012/06/creative-ways-to-repurpose-reuse-and-upcycle-old-things/</strong></a></p>'
 where id=2 ;



Update challenges set environmental_issues='
<p>Did you know that only 0.007 percent of our planet''s water is available to fuel and feed its 7.7 billion population?</p>
<p>Water is the fundamental source of all life on our planet. It is difficult to envision a world where water is depleted or available only to a select few. With careless practices and willful ignorance, it won&rsquo;t be too long when water may become a luxury commodity.</p>
<p>One of the best practices to adopt for water conservation is rainwater harvesting. The water that falls on your roofs during rain is essentially free of cost. Instead of letting it flow to drainages, why not harvest it and use this water instead?</p>
<p>Using rainwater harvesting systems to supply water for some, or all of your water needs, will reduce your water bills and your dependence on groundwater or municipally treated water. This water can be used for variety of purposes such as irrigation, cleaning, etc.</p>' where id=3 ;
Update challenges set participation_steps ='
<p>By 2025, two-thirds of the world population is estimated to live in water-stressed regions. Change your water habits today and make a significant dent in water conservation.</p>
<ul>
<li style="padding-left:10px;">Install a rainwater harvesting system in your home to satisfy some or all of your water needs.</li>
</ul>' where id=3 ;
 Update challenges set reference ='
<p><strong>Read more about Rainwater Harvesting in India: </strong><a href="http://www.yourarticlelibrary.com/water/rain-water-harvesting-in-india-need-methods-and-other-details/20917"><strong>http://www.yourarticlelibrary.com/water/rain-water-harvesting-in-india-need-methods-and-other-details/20917</strong></a></p>
<p><strong>&nbsp;</strong></p>
<p><strong>Build your own rainwater harvesting system: </strong><a href="https://www.wikihow.com/Build-a-Rainwater-Collection-System"><strong>https://www.wikihow.com/Build-a-Rainwater-Collection-System</strong></a></p>' where id=3 ;



Update challenges set environmental_issues='
<p>Littering our neighborhood is not only a culpable habit but also a very expensive one. Carelessly discarded garbage affects every member of society.</p>
<p>When we litter, we create a harmful chain of events that take a toll on the world&rsquo;s health. It makes our neighborhood look bad, causes harm to people and animals, damages our waterways, costs us money and suggests that we do not care for our environment.&nbsp;&nbsp;Litter ultimately adds to the unmonitored waste generated and causes air, water, soil and plastic pollution.</p>
<p>All this can be preempted by maintaining a cleaner neighborhood. You can organize a community cleanup with friends and family to clean your neighborhood and spread awareness about the harmful effects of litter. This can also be an eco-friendly way to bond and show your concern for the nature.&nbsp;</p>' where id=4 ;

Update challenges set participation_steps ='
<p>Do you have unsightly litter in your local area and want to do something about it? Then organize a community clean-up!</p>
<ul>
<li style="padding-left:10px;">Visit a local public spot with your team mates or your family and remove the litter in the area.</li>
<li style="padding-left:10px;">Team up with organizations like Youth for Seva, the Ugly Indian and Say Trees and join them at their spot fix events.</li>
</ul>' where id=4 ;
Update challenges set reference ='
<p><strong>Watch this inspiring TEDx talk on the importance of maintaining a clean environment: </strong><a href="https://www.youtube.com/watch?v=tf1VA5jqmRo"><strong>https://www.youtube.com/watch?v=tf1VA5jqmRo</strong></a></p>' where id=4 ;


Update challenges set environmental_issues='
<p>Most of the food that we eat today has traveled a long distance to reach us. We are also almost always unaware of how or where it is grown. The knowledge of any chemicals used to grow the food are masked to the consumer. What we should know is that this is adversely affecting our environment. The pollution due to chemical use and long-distance transportation can be easily avoided by choosing locally produced food.</p>
<p>Fruits, vegetables, dairy products, eggs and meat are some of the materials that can be easily procured from your local producer. Locally grown food creates important economic opportunities, provides health benefits and helps to reduce environmental impact. It also helps bring the community together and gives people the opportunity to make a difference.&nbsp;</p>
<p>A local food network involves relationships between food producers, distributors, retailers, and consumers in a particular place, where they work together to increase food security and ensure economic, ecological and social sustainability of a community.</p>' where id=5 ;
Update challenges set participation_steps ='
<p>Did you know that many people feel local food tastes better and lasts longer and it is satisfying to&nbsp;know exactly where their food came from and how it was grown? Start your local food journey today.</p>
<ul>
<li style="padding-left:10px;">Locate your local market and recognize food that is grown near to your locality.</li>
<li style="padding-left:10px;">Buy your raw materials from this market for one week.</li>
</ul>' where id=5 ;
 Update challenges set reference ='
<p><strong>Read more on the importance of Local Food: </strong><a href="https://foodrevolution.org/blog/why-buy-local-food/"><strong>https://foodrevolution.org/blog/why-buy-local-food/</strong></a></p>' where id=5 ;



Update challenges set environmental_issues='
<p>Did you know that the rate of deforestation is equal to loss of twenty football fields every minute? The magnitude in which we are losing our trees is unimaginable. If this continues it is estimated that it will take less than 100 years to lose all our rainforests.</p>
<p>The benefits of trees are innumerable. They produce around 50% of the world&rsquo;s oxygen, harbor thousands of species and naturally help to cool our planet. With air pollution on the rise and wildlife on the decline, there&rsquo;s never been a bigger need for reforestation.&nbsp;</p>
<p>Making our city greener carries many advantages to the society. Planted in the right places around buildings, trees can significantly reduce air-conditioning costs.&nbsp;This also means less
' where id=6 ;
Update challenges set environmental_issues=concat(environmental_issues,'&nbsp;<a href="http://en.wikipedia.org/wiki/Dichlorodifluoromethane"><span style="color: windowtext; text-decoration: none; text-underline: none;">Freon</span></a>, an inflammable and odorless chemical emitted from air conditioners - which is considered to have&nbsp;<a href="http://wiki.answers.com/Q/Is_a_freon_leak_harmful_to_the_environment"><span style="color: windowtext; text-decoration: none; text-underline: none;">damaging effects</span></a>&nbsp;on the ozone layer.</p>
<p>Trees also have an undeniable effect on our mental health. Statistics show that workers are more productive when they see trees along their commute routes and from their office windows. Planting trees is one of the easiest ways to positively affect the environment.&nbsp;Take your pledge today and plant a tree!</p>')
 where id=6 ;
Update challenges set participation_steps ='
<p>Planting trees is not only necessary for the future, but it is crucial to do damage control for the past centuries reckless deforestation. Did you know that loss of trees accounts to 12-17 percent of annual global greenhouse gas emissions? Work off your carbon debt today by planting trees.</p>
<p><span style="font-size: 11.0pt; font-family: ''Calibri'',sans-serif;">Plant 5 trees. </span></p>' where id=6 ;

Update challenges set reference ='
<p><strong>Read more on what kind of tree to plant, and how to properly plant a tree: </strong><a href="https://www.wikihow.com/Plant-a-Tree"><strong>https://www.wikihow.com/Plant-a-Tree</strong></a></p>
<p><strong>Check out this video on 6 easy steps to planting a tree: </strong><a href="https://youtu.be/o03jWE8rrXE"><strong>https://youtu.be/o03jWE8rrXE</strong></a></p>' where id=6 ;



Update challenges set environmental_issues='
<p>Do you look beyond the brand when you buy a new dress or shirt? It is difficult to think about, but important to understand that when it comes to what you are wearing - it&rsquo;s not just about your clothes, but the&nbsp;materials and chemicals used to make them.&nbsp;</p>
<p>One of the most used raw materials of the fashion industry &ndash; Cotton, is also the one of the most pesticide-intensive crops. It requires massive quantities of pesticides and water when compared with other crops. 85 % of the daily needs in water of the entire population of India would be covered by the water used to grow cotton in the country.&nbsp;</p>
<p>The fashion industry is cited as the second-most polluting industry, just after the oil industry. The ecologically dangerous biproducts of this industry are pesticide overuse, dumping of hazardous chemicals into oceans, emissions of pollutants and widespread exploitation of industry workers.</p>
<p>Our clothing also contributes significantly to the ever-piling landfills. It is said that only 15 percent of our old clothes is recycled or donated, the rest ending up as waste at landfills. Majority of our clothes made of synthetic fibers take up to 200 years to decompose.</p>' where id=7 ;

Update challenges set participation_steps ='<p>It may be hard to envision that your fashion choices have a substantial impact on our environment. Giving importance to minute details of the clothes you buy can help you make environment sensitive fashion choice.</p>
<p>Complete any one of the challenges below.</p>
<ul>
<li style="padding-left:10px;">Watch an eye-opening documentary along with your team to gain awareness on topics such as Fast Fashion. </li>
<li style="padding-left:10px;">Don&rsquo;t let your clothes end up in landfills. Participate in the Around the World &lsquo;Clothes Swap&rsquo;.</li>
</ul>' where id=7 ;
Update challenges set reference ='
<p><strong>Check out some of these eye-opening documentaries on the fashion industry: </strong><a href="https://www.thefashionspot.com/life/709299-best-fashion-documentaries-on-netflix/"><strong>https://www.thefashionspot.com/life/709299-best-fashion-documentaries-on-netflix/</strong></a></p>
<p><strong>Read this interesting blog on clothes swapping: </strong><a href="https://www.thesimpledollar.com/how-and-why-to-host-a-clothing-swap/"><strong>https://www.thesimpledollar.com/how-and-why-to-host-a-clothing-swap/</strong></a></p>' where id=7 ;



Update challenges set environmental_issues='
<p>Creating awareness about key environment issues begins at home. Children today will have to face the environmental challenges of tomorrow. By educating our children, the next generation will better understand the importance of protecting our planet. It is important for us to do all we can to ensure that the next generation is aware of the challenges that face them in sustaining and protecting our planet, and to provide them with the knowledge and tools to make this happen.</p>
<p>By making them aware of key issues like air and water pollution, energy wastage, ineffective waste disposal, etc., we give them a change to lead a responsible lifestyle. They will know from an early age what a carbon footprint is and why it is important to keep it as low as possible. They will appreciate why upcycling and recycling are the key to reducing the amount of waste we produce, as well as the importance of developing and producing renewable energy.</p>
<p>Making slight changes in their everyday routine will help them have a greener footprint. Habits like turning off water while brushing their teeth, switching off lights when quitting a room, not littering garbage, taking shorter showers, reducing food waste, reuse and recycle old items, etc. can bring a green shift to their attitude towards environment. </p>' where id=8 ;

Update challenges set participation_steps ='<p>Ultimately that world we inhabit today is on a loan from the future generation. Let us equip them with knowledge and habits to protect the planet in the future. </p>
<ul>
<li style="padding-left:10px;">Make the topic of your dinner conversation/spend an hour with your family to discuss an environmental issue which you can closely relate to. Challenge your family to take up any one of the challenges from the campaign for a week!  </li>
</ul>' where id=8 ;

Update challenges set reference ='
<p><strong>Read more: <a href="https://emagazine.com/children-and-the-environment/">https://emagazine.com/children-and-the-environment/</a></strong></p>' where id=8 ;



Update challenges set environmental_issues='
<p>Do you always reach for a straw when you purchase a drink? These little straws are causing an unrecognized impact on our environment. The plastic straws are designed to be single use products, and when tossed away, they add to the global scenario of plastic pollution. The plastics that are used to make straws are recyclable in theory, but they mostly end up in either landfills or at the bottom of the ocean. </p>
<p>Ever since the invention of first synthetic plastic in 1907, plastics have been used by variety of industries for multiple purposes. In 2015, the plastic consumption worldwide totaled 300 million metric tonnes. Because of the way these new, manufactured polymers are heated up and cured, many plastics can''t ever truly be recycled. They might sit in a landfill, or litter a street, for thousands of years without decomposing.</p>
<p>The anti-straw movement can be seen as the first step towards awareness about plastic pollution. When we consciously make an effort to abandon these single-use plastics, we align ourselves with greener lifestyle that endorses a no-plastic policy.</p>' where id=9;

Update challenges set participation_steps ='<p>It is time to become conscious of the plastic waste generated. Begin this journey today by saying no to plastic straws.</p>
<ul>
<li style="padding-left:10px;">Do not use single-use plastic straws for three weeks. Carry a reusable straw with you always or go straw less whenever you can.  </li>
</ul>' where id=9;

Update challenges set reference ='
<p><strong>Check out this short video on plastic straw pollution: <a href="https://www.youtube.com/watch?v=pdTBG929mgs">https://www.youtube.com/watch?v=pdTBG929mgs</a></strong></p>
<p>Buy your reusable straw today: <a href="https://www.thebetterindia.com/shop-metal-straw/">https://www.thebetterindia.com/shop-metal-straw/</a></p>
' where id=9;



Update challenges set environmental_issues='
<p>It may seem innocent that you buy a plastic water bottle or a cup of coffee to quench your thirst. Once you drink your fill, you dispose them within an hour, never to think of them again. </p>
<p>Where do they end up and why is it a concern to the environmentalists? The sad story of plastic bottles is that 35 billion of them end up in landfills each year. The amount is staggering and so is its negative impact on the environment. Although 23 percent of these bottles are recycled, it isn’t enough to balance consumption and disposal. We are failing to find a feasible solution for these discarded single-use plastic bottles. </p>
<p>The story of single-use cups is no different. 50 billion paper cups end up in landfills. This amount is enough to create a waste mountain of coffee cups alone. To make matters worse, paper cups are not recyclable because of the plastic liner and coffee contamination.</p>' where id=10;

Update challenges set participation_steps ='<p>Refuse and Reuse.</p>
<p>If we consider that each person consumes around an average of 34 gallons of water per year, he essentially disposes 217 plastic water bottles. Same goes with coffee cups. If you use one coffee cup per day, you will dispose 365 coffee cups in a year. By simply switching to reusable water bottles and coffee mugs, you prevent your share of waste going into landfills.
</p>
<ul>
<li style="padding-left:10px;">Bring your own coffee mug and water bottle during the entire campaign. </li>
</ul>' where id=10;

Update challenges set reference ='
<p><strong>Read this blog about how you can make bringing your own bottle/mug to work a habit: <a href="https://www.thelittleblackcoffeecup.com/journal/byom">https://www.thelittleblackcoffeecup.com/journal/byom</a></strong></p>' where id=10;




Update challenges set environmental_issues='
<p>Nature makes sure that everything in it has a use — the rotting zucchini, as well as the lavender sprouting scented blossoms in the backyard. Food scraps and yard waste together currently make up about 30 percent of what we throw away and should be composted instead. Making compost keeps these materials out of landfills where they take up space and release methane, a potent greenhouse gas. So, how do we recycle and reuse? It’s actually just one simple process: </p>
<p>Home composting is about taking most of our leftovers, waste and unwanted extras and turn them into fertile soil. You can mix yard and kitchen waste in a pile or bin and provide the right conditions to encourage decomposition. Let bacteria go to work, recycling waste material into usable fertilizer. This can have a significant impact on the productivity of gardens and landscapes. </p>
<p>Compost also has a host of benefits. Firstly, it’s free. You get to use kitchen waste, lawn clippings, leaves – all things that you would have otherwise thrown away. Potting mixes and soils that are rich in compost produce vigorous plants regardless of whether you’re growing vegetables, growing herbs or organic rose gardening. Home composting also improves garden soil structure, texture and aeration. More importantly, it feels good. When else can you turn trash into treasure?
</p>' where id=11;

Update challenges set participation_steps ='<p>Don’t throw away organic waste. They are treasure in disguise. </p>
<ul>
<li style="padding-left:10px;">Set up your own composting pit at home. </li>
</ul>' where id=11;

Update challenges set reference ='
<p><strong>Read more: <a href="https://www.planetnatural.com/home-composting/">https://www.planetnatural.com/home-composting/</a></strong></p>' where id=11;





Update challenges set environmental_issues='
<p>When was last time you received or gave a gift to someone? Perhaps, not too long ago. Giving gifts to our friends and families is a very common practice. What if we said that you can use this practice to create awareness about various environmental issues in your community?  </p>
<p>Green gifting is an emerging trend that can lower the environmental impact created by gift-giving. A green gift can be any gift-worthy item as long as it is made using fewer resources and produces less waste than usual. You can choose gifts that have one or many of these qualities – non-toxic, waste reducing, sustainably-sourced, durable and minimally packaged. You could alternatively also buy something that could help somebody go green, for example – a reusable coffee mug or straw. </p>
<p>Green Gifting can be a wonderful opportunity to spread awareness, start practices like recycling and upcycling and urge your friends and family members to do the same. Even re-gifting (gifting never used or rarely used items) which is usually frowned upon - is encouraged as a viable green gifting option. The philosophy behind green gifting is to create as low an environment impact as possible. </p>' where id=12;

Update challenges set participation_steps ='<p>Gifting thoughtfully and sustainably can create a ripple effect. It might inspire the person you gift to continue the gesture in the future. </p>
<ul>
<li style="padding-left:10px;">Gift an eco-friendly, reusable, recycled or upcycled product to your team mate or friends to help them go green. </li>
</ul>' where id=12;

Update challenges set reference ='
<p><strong>Read more about Green Gifting and identifying the right gifts: <a href="http://www.ecoideaz.com/showcase/try-green-gifting-new-year">http://www.ecoideaz.com/showcase/try-green-gifting-new-year</a></strong></p>' where id=12;




Update challenges set environmental_issues='
<p>It’s easy to forget that there are millions of other species on Earth apart from ourselves. When you live in a bustling city with traffic and huge building being the common view, we tend to forget about the care and requirements of our co-inhabitants of our planet.  </p>
<p>There is already undeniable evidence that animals and birds are being affected by climate change and global warming in both their distribution and behavior.</p>
<p>As the biological systems across the world get affected, it is important to mitigate the effect it has on animals around us. Many non-profit organizations across your city are working relentlessly for the care and benefit of many animals. Volunteering your time to NGOs dedicated to animal support is the best way to do your part to the ongoing campaign for animal protection. </p>' where id=13;

Update challenges set participation_steps ='<p>Share love, resources and time with the animals. </p>
<ul>
<li style="padding-left:10px;">Volunteer 5 hours of your time with an NGO dedicated to animal protection and conservation. </li>
</ul>' where id=13;

Update challenges set reference ='
<p><strong>Read about the benefits of volunteering for animals: <a href="https://www.ccspca.com/blog-spca/benefits-animal-shelter-volunteer/">https://www.ccspca.com/blog-spca/benefits-animal-shelter-volunteer</a></strong></p>' where id=13;



Update challenges set environmental_issues='
<p>It is said that a glass bottle takes a million years to degrade. This means that when a glass bottle isn’t recycled, it remains like that at landfills for a really long time. Glass is primarily composed of silica—the same material as sand—and doesn’t break down even under the harshest environments. Whereas, a humble apple core takes only two months. Our waste is a far bigger problem than you can imagine. </p>
<p>You can understand this better if you visit a landfill where your neighbourhood garbage is hauled off. It will give you an idea of the humongous amount of garbage we throw out every day. Aluminum cans, discarded clothing, rubber soled shoes, plastic cups… and the list never really ends. </p>
<p>You will also be amazed at the time these things take to degenerate. </p>
<p><table>
<tr><td>Glass bottles </td><td>&nbsp;-&nbsp;</td><td> one million years</td></tr>
<tr><td>Disposable nappies </td><td>&nbsp;-&nbsp;</td><td> 450 years </td></tr>
<tr><td>Plastic bottles </td><td>&nbsp;-&nbsp;</td><td> 450 years </td></tr>
<tr><td>Plastic bags </td><td>&nbsp;-&nbsp;</td><td> 200-500 years </td></tr>
<tr><td>Aluminum cans </td><td>&nbsp;-&nbsp;</td><td> 80-200 years </td></tr>
<tr><td>Rubber-soled shoes </td><td>&nbsp;-&nbsp;</td><td> 50-80 years </td></tr>
<tr><td>Tin cans </td><td>&nbsp;-&nbsp;</td><td> 50 years </td></tr>
<tr><td>Clothing </td><td>&nbsp;-&nbsp;</td><td> Up to 40 years </td></tr>
<tr><td>Plastic film </td><td>&nbsp;-&nbsp;</td><td> 20-30 years.</td></tr>
</table></p>
<p>So, what does this tell us? That we must think of the environmental impact when we discard anything. We need to extra careful of what we throw out. The unseemly mound of discard should set us all thinking. </p>' where id=14;

Update challenges set participation_steps ='
<ul>
<li style="padding-left:10px;">Visit a nearby landfill with your friends, teammates or family. </li>
<li style="padding-left:10px;">Notice items which you have used in your everyday life and read about how long different products take to degenerate. </li>
<li style="padding-left:10px;">Pick one item from the landfill that you can recycle or upcycle. </li>

</ul>' where id=14;

Update challenges set reference ='
<p><strong>Want to know more before your visit? Read more here: <a href="https://greenliving.lovetoknow.com/Environmental_Problems:_Landfills">https://greenliving.lovetoknow.com/Environmental_Problems:_Landfills</a></strong></p>' where id=14;




Update challenges set environmental_issues='
<p>Is gardening a favorite pastime of yours? If yes, do you know the composure of the fertilizers and pesticides you use? The most conveniently available and reasonable prized fertilizers and pesticides are chemical in nature. While they do increase the nutrient value of your soil and the growth of your plants, they have serious consequences when used in the long run. </p>
<p>Some of the harm chemical fertilizers may cause include waterway pollution, chemical burn to plants,
increased air pollution, groundwater contamination, acidification of the soil and mineral depletion of the soil. Used over time, they reduce the quality of your natural soil and make them extensively reliant on chemicals. Chemical pesticide exposure can have many adverse effects on us and other non-target organisms. </p>
<p>Organic alternatives to these gardening aids are the best option in terms of long term soil health and environmental impacts. As organic fertilizers and pesticides come from organic sources such animal manure and plants, they improve soil structure and increase their ability to hold water. Ultimately, they are renewable, biodegradable, sustainable, and environmentally friendly.</p>
<p>Mulching – covering soil around the plant with organic material such as grass clippings, crushed leaves, hardwood chips and pine straw – can be an adopted as an effective practice in your garden to act as natural soil conditioners. Mulching contributes to soil health, helps it retain moisture, reduces water injury and helps with weed control.
</p>' where id=15;

Update challenges set participation_steps ='<p>Share love, resources and time with the animals. </p>
<ul>
<li style="padding-left:10px;">Volunteer 5 hours of your time with an NGO dedicated to animal protection and conservation. </li>
</ul>' where id=15;

Update challenges set reference ='
<p><strong>Read about the benefits of volunteering for animals: <a href="https://www.ccspca.com/blog-spca/benefits-animal-shelter-volunteer/">https://www.ccspca.com/blog-spca/benefits-animal-shelter-volunteer</a></strong></p>' where id=15;




Update challenges set environmental_issues='
<p>There are many reasons for lighting up with sunlight. Solar energy is sustainable, renewable, and plentiful. And with the cost of using solar to produce electricity going down each year, many homes are increasingly switching to solar. Here are some major benefits of switching to solar electricity.</p><p>
The solar resource we have enormous. In fact, just one hour of noontime summer sun can provide humongous amount of electricity, powering millions of homes. Solar power is also a major boon to the environment. Each kilowatt-hour(kWh) of solar energy that is generated will substantially reduce greenhouse gas emissions like CO2, as well as other dangerous pollutants such as Sulfur Oxides, Nitrogen Oxides and particulate matter. Solar power also reduces water consumption and withdrawal.</p>
<p>Another advantage is that tapping into solar power will increase the value of your home. Solar panels are viewed as upgrades, like a renovated kitchen or a finished basement. So, leveraging solar power upgrade adds to your home’s value. Research shows that homeowners pay premium prices for solar homes. </p>
<p>Solar electricity boosts your electricity independence. By investing in solar, you can protect yourself against unpredictable utility prices and enjoy economical electricity – the sun will never increase its rates.
</p>' where id=16;

Update challenges set participation_steps ='<p>Tap into the free source of solar energy today and become energy independent. </p>
<ul>
<li style="padding-left:10px;">Install solar panels on your roofs to partially or fully supply power to your home.</li>
</ul>' where id=16;

Update challenges set reference ='
<p><strong>Read more about choosing Solar Panels: <a href="https://www.ecosoch.com/?gclid=Cj0KCQiA1sriBRD-ARIsABYdwwEP8CD8L-5ZKSzUMCogePMuJn1IjBWm3dOhIourWpPvzE-ovU4TCkAaAlbzEALw_wcB">https://www.ecosoch.com/?gclid=Cj0KCQiA1sriBRD-ARIsABYdwwEP8CD8L-5ZKSzUMCogePMuJn1IjBWm3dOhIourWpPvzE-ovU4TCkAaAlbzEALw_wcB</a></strong></p>
<p><strong>Read about Solar Power in India in 2019: <a href="http://sukam-solar.com/solar-for-home/">http://sukam-solar.com/solar-for-home/</a></strong></p>' where id=16;



Update challenges set environmental_issues='
<p>Public transportation may seem less comfortable than travelling in the luxury of your own car, but it’s one of the amazing ways to travel and enjoy your journey. A recent research indicated that a full carriage bus, in a public transport system is equivalent to about 55 cars on the road with one occupant. So, if we all use public transport, we will probably be decongesting more than 50 cars every bus load!</p>
<p>This obviously means that you will be taking a big step in easing traffic congestion. Most of the road traffic bottlenecks witnessed across all roads, across all cities in the world are all attributed to the use of private vehicles and the notion of everyone wanting to use their own personal cars for privacy and comfort. And we keep complaining of traffic jams.</p>
<p>When you pool and travel, you help in reducing the overall environmental greenhouse gas emissions. Greenhouse gas pollution is ever on the rise by using public transport, you’ll be able to cut back on these emissions by more than half. Research has proved that only three to eight people on a public transport bus are able to cut emissions by half compared to an individual commuting in a personal car by himself or herself.</p>
<p>Public transportation allows you to relax. With public transportation, you’ll be able to have your own time, take a nap, avoid the road rage, and get out of the pressures of driving your own private car. During the commute, you can also read or just enjoy the view which will help in boosting your dopamine hormones and reducing your stress levels.</p>
<p>Furthermore, using public transport to travel helps you unwind. Shared mobility is the way to sustainable future.
</p>' where id=17;

Update challenges set participation_steps ='
<ul>
<li style="padding-left:10px;">Use mass transport, bicycles or carpooling once a week, for 3 weeks. This will reduce the usage of private vehicles, thereby decreasing pollution.  </li>
<li style="padding-left:10px;">Use apps such as <b>Quick Ride</b>, where you can carpool or bikepool and also network with other professionals.  </li>
</ul>' where id=17;

Update challenges set reference ='
<p><strong>Check out these interesting articles on carpooling, and why you should use public transport:  <a href="http://citizenmatters.in/carpooling-ride-sharing-apps-sride-wow-zoomcar-traffic-5631">http://citizenmatters.in/carpooling-ride-sharing-apps-sride-wow-zoomcar-traffic-5631</a></strong></p>
<p><strong><a href="https://www.conserve-energy-future.com/extraordinary-reasons-you-should-use-public-transport.php">https://www.conserve-energy-future.com/extraordinary-reasons-you-should-use-public-transport.php</a></strong></p>' where id=17;




Update challenges set environmental_issues='
<p>Have you recently visited a book shop? Stacks of books are piled up waiting for their purchaser. The books that remain on the shelves have a different story to tell. Did you know that over 1.5 million metric tons of paper is used for book publishing in the US alone? If we join the statistics of the rest of the world, this amount will staggeringly increase resulting in a worrying carbon footprint. </p>
<p>Transportation of the books from the printers to bookstores ranging across cities also add to the carbon footprint of the industry. Billions of these books published end up unpurchased. They are either sent back for pulping or end up in landfills. The sad truth is that the book industry is hurting the planet through inefficient manufacturing, distribution, and forecasting of sales.  </p>
<p>While many changes can be made in the publishing industry, as readers we can do our part in reducing the impact of environment. The most sustainable option for a print book lover is the library because books are lent out and read many times. Borrowing books satisfies your thirst of reading and at the same time saves paper, money and energy that goes into new books. </p>
<p>With the ongoing digital revolution, the popularity of e-books is on the rise. The beauty of e-books is their ready accessibility and of course their non-use of paper. They may be the easiest way to stop the destructive cycle of overprinting and pulping. </p>
<p>Donate books after reading and consider buying from used book store. They create a book cycle that do not harm the environment like printing new books do.
</p>' where id=18;

Update challenges set participation_steps ='
<p>Let’s not let our love for reading affect our environment. Choose alternatives to print books that have a lower or nil adverse impact on the environment. </p>
<ul>
<li style="padding-left:10px;">Borrow from libraries instead of buying personal books. Invest in e-books instead of print books. </li>
<li style="padding-left:10px;">Donate books. Purchase from used-book stores when buying books. </li>
</ul>' where id=18;

Update challenges set reference ='
<p><strong>Want to know more about greening your reading habits? Check out these articles: <a href="http://www.thegreenestdollar.com/2009/02/3-cool-ways-to-green-your-reading-habit/">http://www.thegreenestdollar.com/2009/02/3-cool-ways-to-green-your-reading-habit/</a></strong></p>
<p><strong><a href="https://www.quirkbooks.com/post/environmentally-friendly-ways-be-reader">https://www.quirkbooks.com/post/environmentally-friendly-ways-be-reader</a></strong></p>' where id=18;


Update challenges set environmental_issues='
<p>The meat industry is a costly affair both to produce meat and the environment tax it charges. Non-vegetarians across the world love their meat. It is major part of many cuisines and quite frankly tastes delicious. But, are you aware of the story behind your meat? </p>
<p>Raising livestock uses substantial amount of natural resources available. The meat industry produces a vast amount of grain to feed livestock. Feeding a huge portion of grain to livestock also is a bit counterproductive, since we could be eating the grain ourselves without wasting resources to produce it.</p>
<p>Precious resources like fuel and water are used extensively in meat production. Approximately 1,850 gallons of water are needed to produce a single pound of beef compared to 39 gallons of water needed to produce a pound of vegetables. Greenhouse gases are also a major factor. Meat production generates significantly more greenhouse gases like carbon dioxide, methane and nitrous oxide, than vegetable production. </p>
<p>Adding a meatless day once a week can go a long way in reducing your personal consumption of meat and thus creating a dent in this resource misuse vortex. Meatless Monday is also an international campaign that encourages people to not eat meat on Monday to improve their health and the health of the planet.
</p>' where id=19;

Update challenges set participation_steps ='
<p>In addition to the environmental benefits, consuming less meat has been proven to reduce the risk of heart disease and diabetes, helps to curb obesity, and improves the nutritional quality of your diet.</p>
<ul>
<li style="padding-left:10px;">Go meatless on Mondays for 3 weeks during the campaign. </li>
</ul>' where id=19;

Update challenges set reference ='
<p><strong>Read more about why you should be a part of Meatless Mondays: <a href="https://spoonuniversity.com/lifestyle/7-reasons-why-you-should-start-meatless-mondays">https://spoonuniversity.com/lifestyle/7-reasons-why-you-should-start-meatless-mondays</a></strong></p>' where id=19;



Update challenges set environmental_issues='
<p>People across the world are talking about how he number of mobile subscribers have crossed billions and the number is only shooting up.</p>
<p>Mobile phones are a major contributor of toxic waste. Around 40 per cent mobile users replace their phones in less than a year, according to 2017 survey by e-commerce site Quikr Bazaar. This is a major chunk of the millions of metric tons of electronic waste (or e-waste) generated annually.  Data is clear that by number, or in terms of quantity, mobile phones are the biggest contributors to e-waste.</p>
<p>Data also says that 80 to 85 per cent of a particular discarded mobile phone can be recycled, a majority of this total recyclable e-waste is dangerously handled by the informal sector, with little regulation. The remaining 15-20 per cent that cannot be recycled, which may include broken glass, crushed plastic and evaporating metallic compounds, end up as landfill or are tossed into nearby drains and waterways. </p>
<p>The problem is that only a miniscule percentage of the e-waste generated is recycled due to poor infrastructure, legislation and framework. This dangerous trend has led to a waste of diminishing natural resources, irreparable damage to environment and health issues of the people working in industry.
</p>' where id=20;

Update challenges set participation_steps ='
<p>Stop discarding mobile phones without care. Safe and regulated disposal is the key to recycling these mobile phones and save this substantial chunk of junk from landfills.</p>
<ul>
<li style="padding-left:10px;">Recycle at least 2 old cell phones at a certified e-waste drop off center to ensure responsible disposal of your e-waste. </li>
</ul>' where id=20;

Update challenges set reference ='
<p><strong>Read about E-waste in India: <a href="http://ewasteindia.com">http://ewasteindia.com</a></strong></p>' where id=20;



Update challenges set environmental_issues='
<p>How many stationery items do you use in a day at office? From notepads to stick files to paper clips, office stationery supply is an unnoticed yet significant part of any business. While the digitization of some businesses processes is inevitable, stationery will always have an important role in the workplace. </p>
<p>With many businesses opting for personalized stationery, millions of notebooks, files, pens, pencils, and many other everyday use items are manufactured in this industry alone. The single-minded production of these items may seem innocuous, but when you consider their larger impact in terms of paper use and plastic use, you see a more destructive big picture. </p>
<p>Single-use pens generate tons of plastic wastes; scratchpads, sticky notes, printing papers, etc. use massive amount of paper. Office stationery also contributes to a significant amount of waste generation from your office. Banning these items is not viable. While some team members may be happy typing notes and making lists on laptops, many still prefer to scribble down their thoughts using a pen and notepad.
</p>' where id=21;

Update challenges set participation_steps ='
<p>One of the implementable solutions to this issue is the to create a common resource pool for office stationery. Items such as smaller note pads, refillable pens, etc. can be collected and stored in a common reserve to supply to all workers. When your need for a file is fulfilled, it can go back to the bin. Any item not used by you can be deposited for other’s usage. Sharing and making stationery a community resource can significantly reduce its wastage. </p>
<ul>
<li style="padding-left:10px;">Place any unwanted, excess or reusable office stationary that you may have in our ‘Around the World’ supply bin so that it can be used by others. </li>
</ul>' where id=21;

Update challenges set reference ='
<p><strong>Check out this interesting link on how you can reduce office stationary: <a href="https://rabidofficemonkey.com/reduce-waste-office-stationery">https://rabidofficemonkey.com/reduce-waste-office-stationery</a></strong></p>' where id=21;


Update challenges set environmental_issues='
<p>Printing on two sides automatically reduces your paper usage by 50%! Although it is an obvious solution to paper wastage, it is only occasionally implemented. We are so accustomed with printing on one side, that we miss giving a thought as to whether it is absolutely necessary before pressing print. </p>
<p>Discarded paper and paperboard contribute to 26 percent of solid municipal waste in landfill sites. That is one fourth of the entire paper’s industries product. The same product which has used up several trees and vast amounts of water in its making. The impact of deforestation is almost fatal to our environment. Any minor change that can positively override this perilous phenomenon is most welcome. </p>
<p>Researchers have found that about half of the documents printed in a typical office are thrown away within 24 hours. Redundantly printing these documents on one side basically just doubles up the waste. Printing both sides can save more than just paper. Duplex printing actually helps conserve water, trees, and energy. When you change your printer’s settings to print automatically on both sides, you can take a bigger step toward going green.
</p>' where id=22;

Update challenges set participation_steps ='
<p>Print your document only when necessary. Digitizing your method of operation helps majorly in paper usage. When printing choose to double up and reduce your impact on environment. </p>
<ul>
<li style="padding-left:10px;">Configure your office printer or copy machine at office and at home, so that it prints on both the sides of the paper.  </li>
</ul>' where id=22;

Update challenges set reference ='
<p><strong>Read more on how you can save paper at work: <a href="https://www.papersavers.ca/blog/6-ways-save-paper-office">https://www.papersavers.ca/blog/6-ways-save-paper-office</a></strong></p>' where id=22;




Update challenges set environmental_issues='
<p>How do you dispose your waste? Do you end up throwing everything in one single bin? If yes, you might want to know that this habit is not so harmless as it might seem. </p>
<p>When you dump all kinds of waste together, you are increasing the effort taken to manually segregate waste into groups like recyclable, non-recyclable, toxic, etc. </p>
<p>Segregated waste is also often cheaper to dispose off because it does not require as much manual or mechanical sorting as mixed waste. It is also important to segregate waste in the interest of public health. In particular, hazardous wastes can cause long-term health problems, so it is very important that they are disposed off correctly and safely and not mixed in with other waste from your home or office.</p>
<p>Landfills are an increasingly pressing problem. Less and less land is available to deposit refuse, but the volume of waste is growing. As a result, segregating waste is not just of environmental importance, but also of economic concern. Effective segregation of wastes means that less waste goes to landfill which makes it cheaper and better for people and the environment. </p>
<p>The most common form of segregation is separating out recyclable waste such as paper, plastic and glass from landfill and compostable waste. The inclusion of other types of waste in recycling containers causes contamination, reducing the quality of recycled paper and plastic products. Contaminated recycled products also sell for less, a loss that gets passed on to the customer. </p>
<p>The simplest way to solve the waste problem is to solve it before it starts, by practicing proper on-site segregation of waste.
</p>' where id=23;

Update challenges set participation_steps ='
<p>Waste Segregation is the first step in a compliant waste management plan that will help the environment as well as public health. </p>
<ul>
<li style="padding-left:10px;">Segregate your waste by setting up three different bins for different kinds of waste. </li>
</ul>' where id=23;

Update challenges set reference ='
<p><strong>Here is some more information on understanding ow to segregate waste effectively: <a href="http://bengaluru.citizenmatters.in/4561-swmrt-solid-waste-management-guidelines-4561">http://bengaluru.citizenmatters.in/4561-swmrt-solid-waste-management-guidelines-4561</a></strong></p>' where id=23;



Update challenges set environmental_issues='
<p>Having your own kitchen garden has many benefits. Firstly, it is a great way for the whole family to be involved and engage in a relaxing and physical activity. Secondly, the fruits and vegetables grown in your own garden will be healthier because they are rich in nutrients. They also considerably reduce the money spent for transporting, water, fertilizers, etc. on the food items which you buy from supermarkets. </p>
<p>Whether you find gardening relaxing or want to adopt a healthy lifestyle by avoiding produce grown with chemicals, you can have your own kitchen garden. </p>
<p>While, traditionally, a kitchen garden is accessible directly from the kitchen, in an apartment, you can innovate to include one in any available space, whether it’s a terrace, balcony or corridor. However, ensure that the area that you choose has sufficient sunlight so that your plants can thrive</p>
<p>After considering the amount of sunlight in the area and the size of the pots, make a list of vegetables, greens and herbs that you would like to grow. Start by planting easy to grow vegetables. Usually, methi (fenugreek) and local varieties of spinach are the best options to start with. Tomato, cucumber and bitter gourd are ideal vegetables for beginner gardeners to grow. Herbs such as mint and coriander, which are used daily in Indian cooking, are also excellent choices. Once you get more confident, you can experiment with more exotic varieties such as lettuce, zucchini and coloured peppers.
</p>' where id=24;

Update challenges set participation_steps ='
<p>One of the disadvantages of urban living is the lack of space in your house or apartment. If you are one of those homeowners who always wanted a house with a large garden where you could grow your own pesticide-free vegetables, the good news is that you can do this even in a small apartment! </p>
<ul>
<li style="padding-left:10px;">Set up a kitchen garden at home and grow 5 varieties of vegetables or herbs that you use every day. </li>
</ul>' where id=24;

Update challenges set reference ='
<p><strong>Here are some helpful links for you to set up your own kitchen garden: <a href="https://balconygardenweb.com/tips-for-starting-a-kitchen-garden">https://balconygardenweb.com/tips-for-starting-a-kitchen-garden</a></strong></p>
<p><strong><a href="https://www.growveg.com/guides/how-to-plan-a-vegetable-garden-a-step-by-step-guide">https://www.growveg.com/guides/how-to-plan-a-vegetable-garden-a-step-by-step-guide</a></strong></p>' where id=24;



Update challenges set environmental_issues='
<p>Having your own kitchen garden has many benefits. Firstly, it is a great way for the whole family to be involved and engage in a relaxing and physical activity. Secondly, the fruits and vegetables grown in your own garden will be healthier because they are rich in nutrients. They also considerably reduce the money spent for transporting, water, fertilizers, etc. on the food items which you buy from supermarkets. </p>
<p>Whether you find gardening relaxing or want to adopt a healthy lifestyle by avoiding produce grown with chemicals, you can have your own kitchen garden. </p>
<p>While, traditionally, a kitchen garden is accessible directly from the kitchen, in an apartment, you can innovate to include one in any available space, whether it’s a terrace, balcony or corridor. However, ensure that the area that you choose has sufficient sunlight so that your plants can thrive</p>
<p>After considering the amount of sunlight in the area and the size of the pots, make a list of vegetables, greens and herbs that you would like to grow. Start by planting easy to grow vegetables. Usually, methi (fenugreek) and local varieties of spinach are the best options to start with. Tomato, cucumber and bitter gourd are ideal vegetables for beginner gardeners to grow. Herbs such as mint and coriander, which are used daily in Indian cooking, are also excellent choices. Once you get more confident, you can experiment with more exotic varieties such as lettuce, zucchini and coloured peppers.
</p>' where id=24;

Update challenges set participation_steps ='
<p>One of the disadvantages of urban living is the lack of space in your house or apartment. If you are one of those homeowners who always wanted a house with a large garden where you could grow your own pesticide-free vegetables, the good news is that you can do this even in a small apartment! </p>
<ul>
<li style="padding-left:10px;">Set up a kitchen garden at home and grow 5 varieties of vegetables or herbs that you use every day. </li>
</ul>' where id=24;

Update challenges set reference ='
<p><strong>Here are some helpful links for you to set up your own kitchen garden: <a href="https://balconygardenweb.com/tips-for-starting-a-kitchen-garden">https://balconygardenweb.com/tips-for-starting-a-kitchen-garden</a></strong></p>
<p><strong><a href="https://www.growveg.com/guides/how-to-plan-a-vegetable-garden-a-step-by-step-guide">https://www.growveg.com/guides/how-to-plan-a-vegetable-garden-a-step-by-step-guide</a></strong></p>' where id=24;




Update challenges set environmental_issues='
<p>Your skin absorbs 60% of everything you put on it. So, take a look at your personal care products and check whether you know their composure. Do they contain any harmful chemicals? </p>
<p>Ironically, many of the products we use to keep our skin healthy are actually doing more harm than good. We all use shampoo, toothpaste, face cleanser, body soap, and lotion, often multiple times a day, but often these products made conventionally are laden with toxic ingredients. From face scrubs to lipstick, personal care products and cosmetics are laced with dangerous ingredients that can cause pollution, kill plants and animals, and impact your health. </p>
<p>The chemical substances used in makeup and other cosmetics do not break down. They accumulate in the world’s ecosystems, slowly poisoning the planet. When washed down our drains, personal care products get recycled into rivers, lakes, and public water systems. This causes harm to various organisms in the water. </p>
<p>As consumers, we can take steps to keep these harmful chemicals out of the environment. Replacing brand products loaded with dangerous chemicals, we can replace them with organically produces products that uses sustainable raw materials. Choosing reusable, eco-friendly packaged products also helps a long way in keeping the plastics out of landfills.
</p>' where id=25;

Update challenges set participation_steps ='
<p>Let’s be conscious and responsible consumers. </p>
<ul>
<li style="padding-left:10px;">Replace 5 of your personal products with alternatives which are devoid of harmful chemicals to your health and the environment such as Diethyl Phthalate, Triclosan, Cocoamidopropyl Betaine and Oxybenzone. </li>
</ul>' where id=25;

Update challenges set reference ='
<p><strong>Read more at the below links: <a href="https://helloglow.co/ingredients-to-avoid-in-makeup-and-skincare-products">https://helloglow.co/ingredients-to-avoid-in-makeup-and-skincare-products</a></strong></p>
<p><strong><a href="https://www.mercola.com/infographics/personal-care-products.htm">https://www.mercola.com/infographics/personal-care-products.htm</a></strong></p>' where id=25;



Update challenges set environmental_issues='
<p>The issue of animal testing has been an important concern and more and more people have turned to cruelty free products to ensure that the product they use daily have not been tested on animals. There’s no excuse for companies to test on animals when there are better alternatives available and joining markets that require animal testing by law is a decision they can forego. </p>
<p>There are companies who have deliberately stayed out of such markets in order to maintain their cruelty-free status. Companies that test on animals in 2018, choose deliberately to test on these animals. When they have made the choice to be cruel, why support them? There are some easy ways to spot cruelty-free products and choose right.</p>
<p>PETA, or the People for the Ethical Treatment of Animals, has always advocated for companies and consumers going cruelty-free. To help their supporters find cruelty-free products and companies, they have created an online search engine on their website that helps users find these products and companies based on various search criteria. You can search for companies in your area or focus on a specific type of product you’re looking for. You can also use the search engine to narrow the results down to only products that are available in your country. </p>
<p>There are other organizations that have similar search engines. For example, the Cruelty Free International website offers a search engine for products that sport the Leaping Bunny logo, which denotes the product is cruelty-free.
</p>' where id=26;

Update challenges set participation_steps ='
<p>The Leaping Bunny organization supports companies that do not test on animals. To find these products on any given shopping trip, check the product label for the Leaping Bunny logo - a simple black outline of a leaping bunny. You will most likely find this logo on the information label, somewhere near the barcode, if the product has one. </p>
<ul>
<li style="padding-left:10px;">Identify and replace 5 products that you currently use with cruelty-free brands available in the market. </li>
</ul>' where id=26;

Update challenges set reference ='
<p><strong>Check out this link on companies which are testing on animals: <a href="https://www.petaindia.com/living/products/caring-consumer/companies-test-animals">https://www.petaindia.com/living/products/caring-consumer/companies-test-animals</a></strong></p>' where id=26;



Update challenges set environmental_issues='
<p>From growing our own plants to buying from supermarkets, the human food journey has remarkably changes over centuries. Now food travels thousands of kilometers before it is served to us. Have you ever wondered who grows these plants, how they are cultivated and who benefits from them? </p>
<p>What do you know about GMOs? They are crops whose genetic makeup has been modified in laboratories using genetic engineering or transgenic technology. With modern GMOs, DNA is taken from a completely different species (like a fish or virus) and inserted into a crop (like a tomato or corn) to transfer genetic traits. </p>
<p>Today, an estimated 80% of the food on supermarket shelves contain GMOs, something not stated on ingredient labels. The long-term health effects of GMOs on both people and planet are virtually unknown. </p>
<p>At the same time, crops that are imported from long distances rarely benefit the farmer directly. Smallholder farmers produce 70% of the world’s food. Yet the global food system poses many obstacles to those who seek to earn a sustainable livelihood by farming. The products we buy today are made by many minimum-wage farmers and workers who are isolated from the huge profits made by the sales. </p>
<p>One of the way to make sure small-scale farmers get their due is to buy Fairtrade certified products. The Fairtrade mark means the product’s ingredients have been produced by small-scale farmer organizations that meet Fairtrade''s social, economic and environmental standards. At its core, Fair Trade advocates for workers like these smallholder farmers. Fair Trade supports workers’ rights, economic and community development, and environmentally friendly production methods.</p>
<p>The aim is to use trade, not aid, to help small-scale farmers; one of the most marginalized groups in the world. When, as consumers, we advocate this cause by buying Fairtrade certified products, we are helping the real producers of our food gin profits and recognition, successfully elimating middlemen monarchy.
</p>' where id=27;

Update challenges set participation_steps ='
<p>Do your share to create a global food system of fair trade and safe food. </p>
<ul>
<li style="padding-left:10px;">Identify 5 products that fall under the category of Fairtrade or non-GMO. Switch to these products. </li>
<li style="padding-left:10px;">Request your local supermarkets to carry non-GMO products. </li>
</ul>' where id=27;

Update challenges set reference ='
<p><strong>Read more about what Fair Trade and non-GMO really means: <a href="https://www.livestrong.com/slideshow/1011054-labels-organic-allnatural-nongmo-fairtrade-really-mean/?slide=1">https://www.livestrong.com/slideshow/1011054-labels-organic-allnatural-nongmo-fairtrade-really-mean/?slide=1</a></strong></p>' where id=27;



Update challenges set environmental_issues='
<p>The human population on earth has grown more in the last 50 years than it did in the previous 4 million years! World Population stands today at 7.7 billion. The children today will be the flag-bearers for environment restoration in the future. A future that is not too distant. </p>
<p>The world is on the brink of degradation. Our actions can either timely intervene the damage or add to it. We need to make sustainable changes to our everyday routine, keeping the future in mind. These small changes will eventually become a cannonball of efforts that will hinder the damage being done to earth. </p>
<p>Educating the school children in environment is the need of the hour. When threated, we need our wits and sound knowledge to face the threat and win against it. Similarly, we need to provide tips, practices and information to the children with which they can face the future environment threats. </p>
<p>The future is uncertain without sustainable measures taken to restore the environment. One of the undeniable measure to spread awareness among the young citizens of earth. Making an impression on them very early can very well save our planet.
</p>' where id=28;

Update challenges set participation_steps ='
<p>Environmental awareness at schools is the right of children. They need to be aware of their own future circumstances and the best ways to secure their future. </p>
<ul>
<li style="padding-left:10px;">Conduct a session with children in nearby schools to create awareness on current environmental issues, and how they can contribute to make a difference. </li>
</ul>' where id=28;

Update challenges set reference ='
<p><strong>Read more on this challenge: <a href="https://www.greenschoolsalliance.org/blogs/60/628">https://www.greenschoolsalliance.org/blogs/60/628</a></strong></p>' where id=28;




Update challenges set environmental_issues='
<p>We all have our own part to play in the ecosystem. Wildlife helps in balancing the ecosystem and provides stability to different natural processes like rainfall, changing of temperature, fertility of soil etc. It is difficult to imagine our world without the millions of species of wildlife surrounding us. </p>
<p>Climate change, unregulated hunting and poaching, pollution, overexploitation and deforestation are adversely affecting wildlife, pushing increasing number of species into the endangered zone. Nurturing wildlife will positively restore balance in our local ecosystem and lend a hand to the global scene. </p>
<p>Creating a wildlife habitat in your own homes can be an excellent way of supporting local wildlife. Wildlife habitat are areas distributed horizontally and vertically across any landscape that fulfill the needs of a specific wildlife species for the basic requirements of food, water, reproduction (nesting), and protection against predators and competitors.</p>
<p>Supporting insects, birds and bees can promote pollination and increase plant life. Nurturing ground animals can increase your garden soil fertility and help them thrive as well. The benefits of such a wildlife habitat is many and is symbiotic in nature. You benefit from the very animal life you help sustain.
</p>' where id=29;

Update challenges set participation_steps ='
<p>The requirements of wildlife habitat vary according to the needs of each species. You can choose to create a species-specific wildlife habitat such as for birds, bees, insects, etc. </p>
<ul>
<li style="padding-left:10px;">Create a backyard wildlife habitat or "naturescape" in your own backyard, patio or deck by incorporating a few basic elements. </li>
<li style="padding-left:10px;">Basic elements include fresh water (i.e., a bird bath and, if in a yard, water low to the ground); plants and feeders that provide nourishment for birds, insects, etc.; and rocks, trees, bushes and/or bird houses for shelter and nesting. </li>
</ul>' where id=29;

Update challenges set reference ='
<p><strong>Here are a few more links on setting up a backyard wildlife habitat: <a href="https://www.audubon.org/news/17-tips-making-your-backyard-wildlife-friendly-budget">https://www.audubon.org/news/17-tips-making-your-backyard-wildlife-friendly-budget</a></strong></p>
<p><strong><a href="http://www.birdsandblooms.com/birding/birding-basics/create-ultimate-backyard-wildlife-habitat">http://www.birdsandblooms.com/birding/birding-basics/create-ultimate-backyard-wildlife-habitat</a></strong></p>' where id=29;




Update challenges set environmental_issues='
<p>Do you pack your lunch to your office? How much waste do you dispose after the meal? Paper napkins, plastic foils, plastic forks and spoons, throw-away bags, single-use cans are some of the waste generated by you during the lunch hour.</p>
<p>Inorganic waste may take hundreds of years to decompose or may not decompose at all. How much of these inorganic wastes do you contribute from your lunch box? If you discard any of the above-mentioned items during lunch, it’s time to stop now. </p>
<p>A small paper napkin may seem innocent enough. But, did you know that every ton paper needs 17 trees, 380 gallons of oil, 4,000 kilowatts of energy, 7,000 gallons of water and ultimately uses three cubic yards of space at the landfill when disposed. Using what is available to you thoughtfully and cutting back your waste generation can save these valuable resources. </p>
<p>Take a step back and consider the organic and reusable replacement to single-use materials you use. Carry a cloth towel that can be washed everyday instead of using paper napkins during lunch. Carry a thermos water bottle and say no to single-use cups and water bottles. Use cutlery from home and substitute it to plastic ones. These simple changes to your lunch box will automatically reduce your share of waste generated.
</p>' where id=30;

Update challenges set participation_steps ='
<p>The best way to reduce trash is not create it.</p>
<ul>
<li style="padding-left:10px;">Pack a waste-free lunch for a week. Change the way you carry your lunch to work by using reusable products that won’t leave any waste behind apart from compostable items. </li>
<li style="padding-left:10px;">Five Simple Ways to Pack a Waste-Free Lunch:
<p>
<table BORDER=2 BORDERCOLOR="#6EA204">
<tr><th style="text-align: center">YES</th><th style="text-align: center">NO</th></tr>
<tr><td>REUSABLE carrier (cloth bag, lunchbox)</td><td>NO throw-away bags</td></tr>
<tr><td>REUSABLE containers</td><td>NO plastic wrap, foil or styrofoam</td></tr>
<tr><td>THERMOS for drinks</td><td>NO single-use cartons or cans</td></tr>
<tr><td>CLOTH NAPKIN to wash and re-use</td><td>NO paper napkins</td></tr>
<tr><td>SILVERWARE to wash and re-use</td><td>NO plastic forks and spoons</td></tr>
</table>
</p>
</li>
</ul>' where id=30;

Update challenges set reference ='
<p><strong>Read more on how to pack a waste-free lunch: <a href="https://www.wikihow.com/Pack-a-Waste%E2%80%90Free-Lunch">https://www.wikihow.com/Pack-a-Waste%E2%80%90Free-Lunch</a></strong></p>' where id=30;